name: .\.venv
channels:
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - numpy=1.16.5
  - pip=19.2.3
  - python=3.6.9
  - tensorboard=2.0.0
  - pytorch=1.3.0
  - pip:
    - torch==1.3.0
    - transformers==2.2.1

