name: .\.venv
channels:
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _pytorch_select=1.1.0
  - absl-py=0.8.0
  - blas=1.0
  - ca-certificates=2019.8.28
  - certifi=2019.9.11
  - cffi=1.12.3
  - cudatoolkit=10.1.168
  - freetype=2.9.1
  - grpcio=1.16.1
  - icc_rt=2019.0.0
  - intel-openmp=2019.4
  - jpeg=9b
  - libpng=1.6.37
  - libprotobuf=3.9.2
  - libtiff=4.0.10
  - markdown=3.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - ninja=1.9.0
  - numpy=1.16.5
  - numpy-base=1.16.5
  - olefile=0.46
  - openssl=1.1.1d
  - pillow=6.2.0
  - pip=19.2.3
  - protobuf=3.9.2
  - pycparser=2.19
  - python=3.6.9
  - setuptools=41.4.0
  - six=1.12.0
  - sqlite=3.30.0
  - tensorboard=1.14.0
  - tk=8.6.8
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - werkzeug=0.16.0
  - wheel=0.33.6
  - wincertstore=0.2
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pytorch=1.3.0
  - torchvision=0.4.1
  - pip:
    - torch==1.3.0

